services:
  lpbe:
    build: .
    container_name: lpbe
    env_file:
      - .env
    volumes:
      - lpbe_storage:/app/storage/app/public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web-penus-network

  postgres:
    image: postgres:17
    container_name: db-lpbe
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - web-penus-network      

volumes:
  pgdata:
  lpbe_storage:

networks:
  web-penus-network:
    external: true
